# NOTE: THIS IS FOR scheduler scripts for both `orchestrator.py` and Docker method
# Process termination settings
timeouts:
  process_shutdown: 15      # Seconds to wait for graceful shutdown before force kill
  token_validation: 5       # Seconds to wait after token renewal to verify success
  
# Retry and error handling
retry:
  max_attempts: 5           # Maximum retry attempts for token renewal before urgent alerts
  urgent_alert_interval: 5  # Seconds between urgent failure alert messages
  
# Scheduling configuration  
scheduling:
  renewal_cycle: 86355      # Seconds between token renewals (23h 59m 15s)
  
# Script file paths
paths:
  binance_script: "binance/run_connector.py"
  zerodha_script: "zerodha/scheduler.py" 
  ibkr_script: "ibkr/scheduler.py"
  ibkr_create_tables_script: "ibkr/create_tables.py"
  
# Logging configuration
logging:
  level: "DEBUG"             # Log level: DEBUG, INFO, WARNING, ERROR
  max_file_size: 104857600  # Maximum log file size in bytes (100MB)
  
# Health monitoring
health:
  check_interval: 30        # Seconds between process health checks
  memory_limit_mb: 2048     # Memory limit per process before restart warning

# IBKR configuration
ibkr:
  market_start_time: "19:20"  # 7:20 PM IST
  market_end_time: "01:35"    # 1:35 AM IST
  connection_retry_delay: 5   # Seconds to wait before retry
  max_retries: 2              # Maximum connection retry attempts
  pre_market_check_minutes: 5 # (in mins) buffer before market opens to perform qdb checks

# Zerodha configuration
zerodha:
  token_renewal_time: "08:00"  # 8:00 AM IST
  data_start_time: "09:10"     # 9:10 AM IST
  data_end_time: "15:35"       # 3:35 PM IST
  market_start_time: "09:15"   # 9:15 AM IST
  market_end_time: "15:30"     # 3:30 PM IST