version: '3.8'

services:
  binance:
    build: 
      context: ./binance
      dockerfile: Dockerfile
    container_name: binance-connector
    volumes:
      - ./.env:/app/.env:ro
      - ./binance/docker-logs:/app/logs
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "run_connector.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - trading-network

  zerodha:
    build:
      context: ./zerodha
      dockerfile: Dockerfile
    container_name: zerodha-connector
    volumes:
      - ./.env:/app/.env
      - ./zerodha/docker-logs:/app/logs
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "scheduler.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge

volumes:
  binance-logs: 
  zerodha-logs: